### ISSUE TITLE
Unable to activate the conda environment locally; add a list of dependencies

### ISSUE THREAD

**Issue by yangmr04** [hjkgrp/SESAMI_web#27]
https://github.com/hjkgrp/SESAMI_web/blob/3db9c768bbb895f102c2bea90c8b6948cd66a464/README.md?plain=1#L51

This is my request for changes regarding the comments made in the JOSS review https://github.com/openjournals/joss-reviews/issues/5429#issuecomment-1541914894 and https://github.com/openjournals/joss-reviews/issues/5429#issuecomment-1542257910 about unable to activate the conda environment. 

First of all, as the SESAMI is designed as a web app, this is not a huge issue. The web version works beautifully!

I believe this is a known difficulty for activating conda environment on a different platform than where the code is developed. I recommend simply adding a list of all python dependencies for people who are unable activating the conda environment, or just wish to run the app without using conda. This should increase the compatibility of the SESAMI app on different operating systems, and provide a clear guide on which python packages are required to run the code. 

Alternatively, one can improve the current `environment.yml`, that requires further debugging and testing. What do you think? Thanks!

**Comment by gianmarco-terrones** [comment]
Hi @yangmr04 and @mbagheri20, thank you for the feedback and the kind words! With [this commit](https://github.com/hjkgrp/SESAMI_web/commit/8603bdeb776d070b7c5c742d755ebe825968c856) I believe I have addressed this issue.

I adjusted the file environment.yml as @mbagheri20 requested, removing all but the big name packages (installing these installs the other packages anyway), removing the prefix line, and removing version information in most cases to allow for easier builds. I checked, and I can make a Conda environment with this environment.yml and run the website as expected with the environment.

I also added a file environment.txt, which contains a list of python dependencies with specific versioning information for the package versions that I use in my original Conda environment when running the website locally. Furthermore, I have adjusted README.md to reflect these changes.

**Comment by yangmr04** [comment]
Hi @gianmarco-terrones, great fix! I can confirm that now the environment.yml can be activated on my MacOS without any problem! I also get the app to run locally with native python by installing the dependent packages from environment.txt. I am happy to close this issue, but we could also wait for @mbagheri20 for further confirmation.
